version: '3'

services:
  # Start postgres, and ensure that data is stored to a mounted volume

  postgres:
    image: 'postgres:15'
    ports:
      - '5534:5432'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freementors
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data

  # start mailhog
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '1055:1055'
      - '8055:8055'
    restart: always
