version: '3'

services:
  # Setup postgres and ensure data is stored to a mounted volume
  postgres:
    image: 'postgres:15'
    ports:
      - '5455:5455'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: freementors
    volumes:
      - ./database/postgres/:/var/lib/postgresql/data

  # Start mailhog
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1055:1055
      - 8055:8055
    restart: always
